@baseUrl = https://www.hellofresh.lu
@country = LU
@locale = en-LU
@brand = hellofresh
@week = 2026-W18
@token = REPLACE_WITH_BEARER_TOKEN
@jsonAccept = application/json
@plansPage = {{baseUrl}}/plans
@weeksPath = {{baseUrl}}/gw/menus-service/weeks?country={{country}}&locale={{locale}}&brand={{brand}}
@weeksCountryOnlyPath = {{baseUrl}}/gw/menus-service/weeks?country={{country}}
@menusBase = {{baseUrl}}/gw/menus-service/menus?country={{country}}&weeks={{week}}&locale={{locale}}

### Bootstrap page
GET {{plansPage}}
Accept: text/html

### Weeks (recommended)
GET {{weeksPath}}
Authorization: Bearer {{token}}
Accept: {{jsonAccept}}

### Weeks (country only)
GET {{weeksCountryOnlyPath}}
Authorization: Bearer {{token}}
Accept: {{jsonAccept}}

### Menus (recommended)
GET {{menusBase}}&take=1
Authorization: Bearer {{token}}
Accept: {{jsonAccept}}

### Menus filtered by product and SKU
GET {{menusBase}}&product=classic-menu&productSku=LU-CB-3-2-0&take=1
Authorization: Bearer {{token}}
Accept: {{jsonAccept}}

### Menus with pagination
GET {{menusBase}}&take=1&skip=1
Authorization: Bearer {{token}}
Accept: {{jsonAccept}}

### Menus with explicit exclude flag (accepted, but live impact not confirmed)
GET {{menusBase}}&exclude=recipes.category%2Crecipes.nutrition%2Crecipes.steps&take=1
Authorization: Bearer {{token}}
Accept: {{jsonAccept}}
