const KNOWN_RESPONSE_SHAPES = {
  weeks: {
    topKeys: ['weeks'],
    sampleWeek: '2026-W17',
    notes: {
      payloadType: 'object_with_weeks_array',
      countryNeededForData: true,
    },
  },
  menus: {
    topKeys: ['items', 'take', 'skip', 'count', 'total'],
    itemKeys: [
      'id',
      'country',
      'product',
      'productSKUs',
      'week',
      'headline',
      'isActive',
      'isComplete',
      'isReadOnly',
      'serializedPreferences',
      'preferences',
      'courses',
      'modularity',
      'surveyTitle',
      'surveyQuestion',
      'surveyBody',
      'surveyOptIn',
      'averageRating',
      'rated',
      'link',
      'createdAt',
      'updatedAt',
      'clonedFrom',
      'mealSwapCombinations',
      'mealSwapCombinationsText',
    ],
    courseKeys: [
      'index',
      'recipe',
      'selectionLimit',
      'isSoldOut',
      'hideOnSoldOut',
      'soldOutThreshold',
      'chargeSetting',
      'isHidden',
      'sections',
      'presets',
      'shoppingSegments',
      'shoppableProductId',
    ],
    recipeKeys: [
      'active',
      'averageRating',
      'category',
      'country',
      'cuisines',
      'difficulty',
      'favoritesCount',
      'headline',
      'id',
      'imageLink',
      'imagePath',
      'ingredients',
      'isPublished',
      'label',
      'name',
      'nutrition',
      'prepTime',
      'ratingsCount',
      'slug',
      'steps',
      'tags',
      'totalTime',
      'uuid',
      'websiteUrl',
      'yields',
    ],
    nutritionEntryKeys: ['type', 'name', 'amount', 'unit'],
    categoryKeys: ['id', 'name', 'slug', 'type'],
    cuisineKeys: ['id', 'name', 'slug', 'type'],
    tagKeys: ['id', 'name', 'slug', 'type', 'displayLabel', 'colorHandle', 'preferences'],
    notes: {
      itemProbe: 'country=LU&weeks=2026-W18&locale=en-GB&product=classic-menu&productSku=LU-CB-3-2-0&take=1',
      ingredientsObservedState: 'empty_array_in_live_probe',
      stepsObservedState: 'empty_array_in_live_probe',
      yieldsObservedState: 'empty_array_in_live_probe',
      nutritionObservedState: 'populated_array_in_live_probe',
    },
  },
};

export function getKnownResponseShapes() {
  return structuredClone(KNOWN_RESPONSE_SHAPES);
}
